- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node
- name: Install N
  become: true
  npm:
    name: n
    global: yes
  tags:
    - install
    - node
- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags:
    - install
    - node
- name: Adding npm-global to PATH
  become: true
  shell: echo PATH=~/.local/.npm-global/bin:$PATH > /etc/environment && . /etc/environment
  tags:
    - install
    - node
- name: Install correct version of Node
  become: true
  shell: n 18
  tags:
    - install
    - node
- name: Install global npm packages
  shell: |
    while read package; do 
      npm install -g $package
    done < $HOME/.dotfiles/other/npm-packages.txt
  tags:
    - install
    - node
