- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Get Packer
  ansible.builtin.git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
- name: Add neovim stable repository
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable
  tags:
    - install
    - neovim
- name: Install neovim
  apt:
    name: neovim
  tags:
    - install
    - neovim
- name: Install ripgrep
  apt:
    name: ripgrep
